security:
  enable_authenticator_manager: true


  password_hashers:
    App\Entity\User:
        algorithm: 'auto'
  providers:
      users:
          entity:
              class: App\Entity\User
              property: email

  firewalls:
      main:
          stateless: true
          provider: users
          json_login:
              check_path: auth # The name in routes.yaml is enough for mapping
              username_path: email
              password_path: password
              success_handler: lexik_jwt_authentication.handler.authentication_success
              failure_handler: lexik_jwt_authentication.handler.authentication_failure
          jwt: ~

  access_control:
      - { path: ^/api/register, roles: PUBLIC_ACCESS }
      - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
      - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI docs
      - { path: ^/auth, roles: PUBLIC_ACCESS }
      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
